name: '[PR] Validation'
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm install --global @salesforce/cli
      - run: npm run bin:js -- -V
      - run: npm run bin:js -- -h
      - run: npm run bin:js create -- -h
      - run: npm run bin:js resource -- -h
