name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  VERSION_TEXT: Incrementing npm package version to
  GET_CURRENT_TAG_CMD: npm pkg get version | tr -d '\"'
jobs:
  publish:
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git add package.json package-lock.json
      - run: echo "VERSION=$(${{ env.GET_CURRENT_TAG_CMD }})" >> $GITHUB_ENV
      - run: git commit -m '${{ env.VERSION_TEXT }} ${{ env.VERSION }}'
      - run: echo '::notice::${{ env.VERSION_TEXT }} ${{ env.VERSION }}'
      - run: git push origin HEAD:${{ github.ref_name }}
