name: 'PR'
on:
  pull_request:
    types: [opened, edited]
jobs:
  validate-title:
    name: Validate Title
    permissions:
      contents: read
      pull-requests: write
    if: always() && (github.event.action == 'opened' || github.event.changes.title.from)
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Add Jira Ticket to Existing PR title
        uses: the-wright-jamie/update-pr-info-action@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          head-branch-regex: 'build|ci|docs|feat|fix|perf|refactor|test'
          title-insert-space: true
          title-update-action: prefix
          title-template: '[%headbranch%]'
